### ISSUE TITLE
3.0 broken, list export not implemented

### ISSUE THREAD

**Issue by fatcrobat** [heimrichhannot/contao-exporter#2] opened 2016-11-30 10:26 UTC
Cant use 3.x versions, as list export not working and 2.2.6 to 3.0 switch throws errors. Tested with lottery module (export participants)

```
Recoverable error: Argument 1 passed to PHPExcel_IOFactory::createWriter() must be an instance of PHPExcel, boolean given, called in /home/rico/Kunden/beg/web/produkte/contao/system/modules/exporter/classes/PhpExcelExporter.php on line 119 and defined in composer/vendor/phpoffice/phpexcel/Classes/PHPExcel/IOFactory.php on line 132
#0 composer/vendor/phpoffice/phpexcel/Classes/PHPExcel/IOFactory.php(132): __error(4096, 'Argument 1 pass...', '/home/rico/Kund...', 132, Array)
#1 system/modules/exporter/classes/PhpExcelExporter.php(119): PHPExcel_IOFactory::createWriter(false, 'CSV')
#2 system/modules/exporter/classes/Exporter.php(77): HeimrichHannot\Exporter\PhpExcelExporter->exportToDownload(false)
#3 system/modules/exporter/classes/PhpExcelExporter.php(35): HeimrichHannot\Exporter\Exporter->export('2', Array)
#4 system/modules/exporter/modules/ModuleExporter.php(47): HeimrichHannot\Exporter\PhpExcelExporter->export('2', Array)
#5 system/modules/exporter/modules/ModuleExporter.php(28): HeimrichHannot\Exporter\ModuleExporter::export(Object(HeimrichHannot\Exporter\ExporterModel), '2')
#6 system/modules/core/classes/Backend.php(430): HeimrichHannot\Exporter\ModuleExporter::exportBe(Object(Contao\DC_Table))
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('lottery')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}

Recoverable error: Argument 1 passed to PHPExcel_Writer_CSV::__construct() must be an instance of PHPExcel, boolean given, called in /home/rico/Kunden/beg/web/produkte/contao/composer/vendor/phpoffice/phpexcel/Classes/PHPExcel/IOFactory.php on line 141 and defined in composer/vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/CSV.php on line 91
#0 composer/vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/CSV.php(91): __error(4096, 'Argument 1 pass...', '/home/rico/Kund...', 91, Array)
#1 composer/vendor/phpoffice/phpexcel/Classes/PHPExcel/IOFactory.php(141): PHPExcel_Writer_CSV->__construct(false)
#2 system/modules/exporter/classes/PhpExcelExporter.php(119): PHPExcel_IOFactory::createWriter(false, 'CSV')
#3 system/modules/exporter/classes/Exporter.php(77): HeimrichHannot\Exporter\PhpExcelExporter->exportToDownload(false)
#4 system/modules/exporter/classes/PhpExcelExporter.php(35): HeimrichHannot\Exporter\Exporter->export('2', Array)
#5 system/modules/exporter/modules/ModuleExporter.php(47): HeimrichHannot\Exporter\PhpExcelExporter->export('2', Array)
#6 system/modules/exporter/modules/ModuleExporter.php(28): HeimrichHannot\Exporter\ModuleExporter::export(Object(HeimrichHannot\Exporter\ExporterModel), '2')
#7 system/modules/core/classes/Backend.php(430): HeimrichHannot\Exporter\ModuleExporter::exportBe(Object(Contao\DC_Table))
#8 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('lottery')
#9 contao/main.php(20): Contao\BackendMain->run()
#10 {main}
```

**Comment by Defcon0** [comment] 2016-12-05 08:33
Thanks for your bug report. The issue is fixed in 3.0.2 :-)

**Closed as completed by Defcon0** 2016-12-05 08:33 UTC
Labels: bug
